"""
report.py
---------
Turns the summary dict from database.py into a formatted PDF report.

THIS FILE KNOWS NOTHING ABOUT:
  - The database (receives a plain dict)
  - Email (that is emailer.py's job)

USAGE:
  from app.report import generate_report
  path = generate_report(summary)
"""

import logging
from datetime import date
from fpdf import FPDF

from app.config import config

log = logging.getLogger(__name__)

# == Design tokens =============================================================
# Change these to restyle the whole report from one place.

BRAND_BLUE    = (26,  86,  219)
BRAND_DARK    = (30,  41,  59)
LIGHT_GRAY    = (248, 250, 252)
MID_GRAY      = (226, 232, 240)
SUCCESS_GREEN = (22,  163, 74)
WARNING_AMBER = (217, 119, 6)
DANGER_RED    = (220, 38,  38)
WHITE         = (255, 255, 255)

PAGE_W    = 210
MARGIN    = 14
CONTENT_W = PAGE_W - MARGIN * 2   # 182mm usable width


# == ReportPDF class ===========================================================

class ReportPDF(FPDF):
    """
    Custom FPDF subclass.
    Overriding header() and footer() means every page gets them
    automatically - we never call them manually.
    """

    def header(self):
        """Full-width brand blue bar at the top of every page."""
        self.set_fill_color(*BRAND_BLUE)
        self.rect(0, 0, PAGE_W, 22, style="F")

        self.set_font("Helvetica", "B", 15)
        self.set_text_color(*WHITE)
        self.set_xy(MARGIN, 5)
        self.cell(0, 12, "Daily Business Report", align="L")

        self.set_font("Helvetica", "", 9)
        self.set_xy(0, 7)
        self.cell(PAGE_W - MARGIN, 8,
                  config.report_date.strftime("%d %B %Y"), align="R")

        self.ln(18)

    def footer(self):
        """Subtle footer on every page."""
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(160, 160, 160)
        self.cell(0, 10,
                  "Auto-generated by Report Bot  |  Do not reply",
                  align="C")


# == Section builders ==========================================================

def _section_title(pdf: ReportPDF, title: str) -> None:
    """Blue left-accent section heading."""
    pdf.set_fill_color(*BRAND_BLUE)
    pdf.rect(MARGIN, pdf.get_y(), 3, 7, style="F")

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*BRAND_DARK)
    pdf.set_x(MARGIN + 5)
    pdf.cell(0, 7, title, ln=True)
    pdf.ln(2)


def _kpi_boxes(pdf: ReportPDF, s: dict) -> None:
    """
    Four KPI boxes in a single row.
    Each box has a colored top bar, a big value, and a small label.
    """
    kpis = [
        ("New Users",       str(s["new_users"]),                   BRAND_BLUE),
        ("Total Orders",    str(s["total_orders"]),                BRAND_DARK),
        ("Total Revenue",   f"INR {s['total_revenue']:,.2f}",      SUCCESS_GREEN),
        ("Avg Order Value", f"INR {s['avg_order_value']:,.2f}",    BRAND_BLUE),
    ]

    box_w   = (CONTENT_W - 6) / 4   # 4 boxes with 3 gaps of 2mm
    box_h   = 22
    gap     = 2
    y_start = pdf.get_y()

    for i, (label, value, color) in enumerate(kpis):
        bx = MARGIN + i * (box_w + gap)

        # Box background + border
        pdf.set_fill_color(*LIGHT_GRAY)
        pdf.set_draw_color(*MID_GRAY)
        pdf.rect(bx, y_start, box_w, box_h, style="FD")

        # Colored top accent bar
        pdf.set_fill_color(*color)
        pdf.rect(bx, y_start, box_w, 2, style="F")

        # Big value text
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(*color)
        pdf.set_xy(bx, y_start + 5)
        pdf.cell(box_w, 7, value, align="C")

        # Small label beneath
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(100, 100, 100)
        pdf.set_xy(bx, y_start + 13)
        pdf.cell(box_w, 5, label, align="C")

    pdf.set_y(y_start + box_h + 6)


def _summary_table(pdf: ReportPDF, s: dict) -> None:
    """
    Two-column table: Metric | Value.
    Alternating row colors for readability.
    Status rows (Completed/Pending/Cancelled) get colored value text.
    """
    report_date_str = (
        s["report_date"].strftime("%d %B %Y")
        if isinstance(s["report_date"], date)
        else str(s["report_date"])
    )

    rows = [
        ("Report Date",       report_date_str),
        ("New Users",         str(s["new_users"])),
        ("Total Orders",      str(s["total_orders"])),
        ("Total Revenue",     f"INR {s['total_revenue']:,.2f}"),
        ("Avg Order Value",   f"INR {s['avg_order_value']:,.2f}"),
        ("Max Order Value",   f"INR {s['max_order_value']:,.2f}"),
        ("Completed Orders",  str(s["completed_orders"])),
        ("Pending Orders",    str(s["pending_orders"])),
        ("Cancelled Orders",  str(s["cancelled_orders"])),
    ]

    row_h = 9
    col_w = [90, CONTENT_W - 90]

    status_colors = {
        "Completed Orders": SUCCESS_GREEN,
        "Pending Orders":   WARNING_AMBER,
        "Cancelled Orders": DANGER_RED,
    }

    # Table header row
    pdf.set_fill_color(*BRAND_BLUE)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_draw_color(*MID_GRAY)
    pdf.set_line_width(0.2)
    pdf.set_x(MARGIN)
    for col_label, w in [("  Metric", col_w[0]), ("Value  ", col_w[1])]:
        pdf.cell(w, row_h, col_label, border=1, fill=True,
                 align="L" if col_label.startswith(" ") else "R")
    pdf.ln()

    # Data rows
    for i, (metric, value) in enumerate(rows):
        fill_color = LIGHT_GRAY if i % 2 == 0 else WHITE
        pdf.set_fill_color(*fill_color)
        pdf.set_draw_color(*MID_GRAY)
        pdf.set_x(MARGIN)

        # Metric cell
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*BRAND_DARK)
        pdf.cell(col_w[0], row_h, f"  {metric}",
                 border=1, fill=True, align="L")

        # Value cell - colored for status rows
        text_color = status_colors.get(metric, BRAND_DARK)
        is_status  = metric in status_colors
        pdf.set_text_color(*text_color)
        pdf.set_font("Helvetica", "B" if is_status else "", 9)
        pdf.cell(col_w[1], row_h, f"{value}  ",
                 border=1, fill=True, align="R")
        pdf.ln()

    pdf.ln(4)


def _order_status_breakdown(pdf: ReportPDF, s: dict) -> None:
    """
    Horizontal bar chart built from FPDF rectangles.
    No external charting library needed - just rectangles and text.
    Each bar shows count and percentage of total orders.
    """
    total = s["total_orders"]
    if total == 0:
        return

    bar_data = [
        ("Completed", s["completed_orders"], SUCCESS_GREEN),
        ("Pending",   s["pending_orders"],   WARNING_AMBER),
        ("Cancelled", s["cancelled_orders"], DANGER_RED),
    ]

    bar_h   = 10
    label_h = 6
    row_gap = 5
    y       = pdf.get_y()

    for label, count, color in bar_data:
        proportion = count / total
        filled_w   = CONTENT_W * proportion

        # Grey background track (full width)
        pdf.set_fill_color(*LIGHT_GRAY)
        pdf.rect(MARGIN, y, CONTENT_W, bar_h, style="F")

        # Colored filled portion
        if filled_w > 0:
            pdf.set_fill_color(*color)
            pdf.rect(MARGIN, y, filled_w, bar_h, style="F")

        # White count inside bar only if bar is wide enough to fit text
        if proportion > 0.15:
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*WHITE)
            pdf.set_xy(MARGIN + 2, y + 2)
            pdf.cell(filled_w - 4, 6, str(count), align="L")

        # Label + percentage always printed BELOW the bar in the bar color
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*color)
        pdf.set_xy(MARGIN, y + bar_h + 1)
        pdf.cell(
            CONTENT_W, label_h,
            f"{label}: {count} orders  ({proportion * 100:.0f}%)",
            align="L"
        )

        y += bar_h + label_h + row_gap

    pdf.set_y(y + 2)


# == Public entry point ========================================================

def generate_report(summary: dict) -> str:
    """
    Build the full PDF from the summary dictionary.

    Args:
        summary: plain dict from database.get_summary_dict()

    Returns:
        str: absolute path to the saved PDF file
    """
    log.info("Generating PDF report...")

    pdf = ReportPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()
    pdf.set_margins(MARGIN, MARGIN, MARGIN)

    _section_title(pdf, "Overview")
    _kpi_boxes(pdf, summary)

    _section_title(pdf, "Detailed Metrics")
    _summary_table(pdf, summary)

    _section_title(pdf, "Order Status Breakdown")
    _order_status_breakdown(pdf, summary)

    pdf.output(config.pdf_path)
    log.info(f"PDF saved to: {config.pdf_path}")

    return config.pdf_path